modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="aerofix"
version="1.0.0"
displayName="Aeronautics Render Fix"
authors="0grox"
description="фиксит баг прорисовки физ построек крейт аеронафтик при переходе в разние измерения или отхождения далеко"