modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
    modId = "create_rvb"
    version = "1.0.0"
    displayName = "Create: Rebuild Vanilla Blocks"
    updateJSON = "https://change.this.to.a.real.url"
    authors = "Mrammor"
    description = '''
    An addon for Create mod that overhauls and rebuilds standard vanilla blocks into functional multi-blocks with connected textures!
    '''

[[dependencies.create_rvb]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.create_rvb]]
    modId = "create"
    type = "required"
    versionRange = "[0.6.1,)"
    ordering = "AFTER"
    side = "BOTH"